"""Second migration

Revision ID: 678ca0a4d8bf
Revises: 173b61c07815
Create Date: 2026-05-21 13:48:59.093026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678ca0a4d8bf'
down_revision: Union[str, Sequence[str], None] = '173b61c07815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('destination_url', sa.String(), nullable=True),
    sa.Column('qr_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_id'), 'scan_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_events_id'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_table('recipients')
    # ### end Alembic commands ###
