server {
    listen 80;
    server_name qrcode.bizeducate.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name qrcode.bizeducate.net;

    ssl_certificate /etc/letsencrypt/live/qrcode.bizeducate.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qrcode.bizeducate.net/privkey.pem;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name analytics.bizeducate.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name analytics.bizeducate.net;

    ssl_certificate /etc/letsencrypt/live/qrcode.bizeducate.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/qrcode.bizeducate.net/privkey.pem;

    location / {
        proxy_pass http://metabase:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
